# Generated by Django 3.2 on 2021-04-13 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTask',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_url', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'Idle'), (1, 'Queuing'), (2, 'Printing'), (3, 'Done')], default=0)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='users.user')),
            ],
        ),
    ]
