# Generated by Django 3.2 on 2021-04-14 03:34

from django.db import migrations, models
import django.db.models.deletion
import prints.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTask',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to=prints.models.user_directory_path)),
                ('status', models.IntegerField(choices=[(1, 'Queuing'), (2, 'Printing'), (3, 'Done')], default=1)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='users.user')),
            ],
        ),
    ]
