# Generated by Django 3.2 on 2021-04-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printtask',
            name='status',
            field=models.IntegerField(choices=[(1, 'Queuing'), (2, 'Printing'), (3, 'Done')], default=1),
        ),
    ]
