# Generated by Django 3.2 on 2021-04-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_current_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_state',
            field=models.CharField(choices=[('NON_REGIS', 'Not Registered'), ('IDLE', 'Idle'), ('PROMPT_PRINT', 'Prompt Print'), ('QUEUEING', 'Queueing'), ('PRINTING', 'Printing')], default='NON_REGIS', max_length=12),
        ),
    ]
